version: '3.8'

services:
  postres_users_db:
    image: postgres:15-alpine
    container_name: 'postgres_users_db'
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=users_db
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_users_data: